def handlers_mainmenu_instructions():
    print()
    print()
    print("Imposter Game Instructions - Before the Round")
    print("The game is best played with 3-8+ players.")
    print("A secret word is chosen and given to all players except the imposter, who is given a hint.")
    print("Everyone must keep their role (word) a secret and try to figure out who the imposter is.")
    input("Press enter to continue...\t")
    
    print()
    print()
    print("Imposter Game Instructions - During the Round")
    print("Players take turns describing the secret word without saying the word or giving it away to the imposter.")
    print("Players cannot repeat words that have been said during the current round. The imposter may say their hint.")
    print("The game starts with a specified player and follows in a specified rotation.")
    print("Each player must describe the word with 1 word or a proper noun (like George Washington).")
    print("Each player must speak twice per round.")
    input("Press enter to continue...\t")
    
    print()
    print()
    print("Imposter Game Instructions - Voting")
    print("After each round, players vote to determine who the imposter is.")
    print("If there is a tie vote, a discussion will take place.")
    print("The imposter must reveal themself after the vote.")
    print("The crewmates win if they correctly identify the imposter, otherwise the imposter wins.")
    input("Press enter to continue...\t")